# Site
name: "Caffinc"
title: "Caffinc Blog"
description: "Caffeine Induced Code and Tech Ramblings"
github_username: caffinc
url: https://caffinc.github.io

#logo: 'assets/images/logo.png'
#favicon: 'assets/images/logo.png'
#baseurl: /mediumish-theme-jekyll
#google_analytics: 'UA-46278016-1'
disqus: 'caffinc'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  admin:
    name: Sriram
    display_name: Sriram
    gravatar: dcb7ddb478428732e807d1a1797bb417
    email: admin@caffinc.com
    web: https://www.caffinc.com
    twitter: https://twitter.com/0k_ram
    description: "Creator of geeky things, mostly unused junk"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-gist
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
